"""empty message

Revision ID: 299228685577
Revises: 
Create Date: 2023-01-15 12:29:48.587632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299228685577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initial_url', sa.String(length=200), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('protocol', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('domain_zone', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initial_url'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
